### PR TITLE
Improve header size on summary page

### PR DESCRIPTION
**Pull request by alamb**
# Rationale
This PR replaces https://github.com/apache/datafusion-site/pull/49 and is mostly to test out the blog publishing pipleine from @timsaucer :heart:

However, it is also fix something that annoys me unreasonably:

Screenshot 2024-12-13 at 11 23 27 AM

# Changes
1. Reduce header sizes in one of the articles

Screenshot 2024-12-13 at 11 32 12 AM

I also double checked that even with the changed header the main article looks reasonable

Screenshot 2024-12-13 at 11 32 37 AM

## Next Steps
If this is an ok change, I will apply the same pattern to the other headings

### CODE REVIEW

**Comment by alamb** [comment]
🤔 the pelican build seems to be broken:

https://github.com/apache/datafusion-site/actions/runs/12319494192/job/34386667171?pr=50

Seems to have a similar report as https://github.com/getpelican/pelican/issues/2983 🤔 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rich 13.7.1 requires pygments<3.0.0,>=2.13.0, but you have pygments 2.6.1 which is incompatible.
Python 3.12.3
Pelican version:
Traceback (most recent call last):
  File "/home/runner/.local/bin/pelican", line 5, in <module>
    from pelican.__main__ import main
  File "/home/runner/.local/lib/python3.12/site-packages/pelican/__init__.py", line 19, in <module>
    from pelican.generators import (ArticlesGenerator,  # noqa: I100
  File "/home/runner/.local/lib/python3.12/site-packages/pelican/generators.py", line 11, in <module>
    from jinja2 import (BaseLoader, ChoiceLoader, Environment, FileSystemLoader,
  File "/home/runner/.local/lib/python3.12/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/runner/.local/lib/python3.12/site-packages/jinja2/environment.py", line [25](https://github.com/apache/datafusion-site/actions/runs/12319494192/job/34386667171?pr=50#step:3:27), in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/runner/.local/lib/python3.12/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.local/lib/python3.12/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3/dist-packages/markupsafe/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by timsaucer** [comment]
Instead of changing the articles, what if we just adjust the css to auto apply a different size?

**Comment by alamb** [comment]
> Instead of changing the articles, what if we just adjust the css to auto apply a different size? I did do a smaller adjustment already, but we can certainly push it further. In https://github.com/apache/datafusion-site/blob/main/content/css/blog_index.css we can adjust the overrides to make them smaller even. That wouldn't change the size on the individual pages, just the index.

Sounds like a great idea to me.

**Comment by timsaucer** [comment]
The change I proposed just merged in and is live. Is that good or do you want it even smaller?

Here is what it looks like on mobile devices 

image

**Comment by alamb** [comment]
I just checked and I think it looks pretty good to me now. Thank you @timsaucer 

I am not a visual designer so maybe someone else with a better eye could finagle it more. It doesn't look at large / outsized to me anymore  

Screenshot 2024-12-21 at 10 30 11 AM


Thanks again

**Pull request closed without merging**
